### PR TITLE
format code

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@XzzX somehow the formatting differs.

**Comment by XzzX** [comment]
You have to run it three times to converge the initial formatting.

**Review by XzzX — CHANGES_REQUESTED** [review]
Please wait for the -Wall PR to be merged or discarded. I fear a lot of merge conflicts.

**Comment by junghans** [comment]
@XzzX rebase and ready to merge!

**Review by XzzX — APPROVED** [review]

**Comment by XzzX** [comment]
@jnvance Can you please have a look at this. This might cause a lot of merge conflicts in your code. If so we should perhaps delay this PR.

**Comment by jnvance** [comment]
LGTM. I've fixed the conflicts in the numpy part and I'm manually fixing and applying format.sh on #334

**Review by jnvance — APPROVED** [review]

**Pull request merged**
