### PR TITLE
cleanup & extension of gitignore

### PR DESCRIPTION
**Pull request by XzzX**
I vote for strictly separating source and build directories.
This would make some ignores obsolete, however, requires a change
in philosophy.

### CODE REVIEW

**Review by junghans — CHANGES_REQUESTED** [review]
Can we leave `*~` in there?

**Comment by XzzX** [comment]
Yes. What is the purpose of this entry?

**Comment by junghans** [comment]
> Yes. What is the purpose of this entry?

Vim backup files

**Comment by XzzX** [comment]
done.

**Review by junghans — APPROVED** [review]

**Pull request merged**
