### PR TITLE
cmake: support python3.10

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@XzzX I have no idea why these test segfault now....

**Comment by junghans** [comment]
@stuehn do you understand this segfault?

**Comment by XzzX** [comment]
> @XzzX I have no idea why these test segfault now....

Does this segfault occur due to this one line change or due to a buildenv rebuild?

**Comment by junghans** [comment]
> > @XzzX I have no idea why these test segfault now....
> 
> Does this segfault occur due to this one line change or due to a buildenv rebuild?

The one line change fixes `PYTHON_VERSION_NO_DOT`, which was `31` for python3.10 instead of the correct `310`.

I think the segfault is due to the buildenv rebuild and the usage of python3.10.

**Comment by XzzX** [comment]
I am no expert with boost.python. In fact I have never used it. I prefer pybind11. Is this a problem:
```
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:2201 (message):
  No header defined for python310; skipping header check (note: header-only
  libraries have no designated component)
Call Stack (most recent call first):
  CMakeLists.txt:92 (find_package)
  ```

**Comment by fedepad** [comment]
Do the cmake modules used support detecting python 3.10?
I see it has been added not long ago: https://github.com/Kitware/CMake/commit/bb2ebbf2412ef9343f50a45868459ffb95fa9081

**Comment by junghans** [comment]
The regex in CMake is `"^(python|mpi_python|numpy)([0-9][0-9]?|[0-9]\\.[0-9])\$"`, so I guess `310` is wrong, it should be `3.10`

**Comment by junghans** [comment]
@XzzX the warning is just saying boostpython has no headers, which makes sense.

@fedepad that patch is already part of our build environment.

**Comment by XzzX** [comment]
=== STATUS REPORT ===
SegFault in `12/84 Test #10: testCapForce .........................***Exception: SegFault  1.18 sec`  
Line of error: `https://github.com/espressopp/espressopp/blob/junghans-patch-2/testsuite/cap_force/testCapForce.py#L111`  
Stacktrace with demangled names:
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007f4d05c749eb in PyDict_GetItemWithError (op=0x7f4cfd7ec3f0 <boost::python::objects::enum_repr(PyObject*)>, key=key@entry=0x55c30af94350) at /usr/src/debug/python3.10-3.10.0-1.fc35.x86_64/Objects/dictobject.c:1513
1513        if (!PyDict_Check(op)) {                                                                 
(gdb) bt
#0  0x00007f4d05c749eb in PyDict_GetItemWithError (
    op=0x7f4cfd7ec3f0 <boost::python::objects::enum_repr(PyObject*)>, key=key@entry=0x55c30af94350)
    at /usr/src/debug/python3.10-3.10.0-1.fc35.x86_64/Objects/dictobject.c:1513
#1  0x00007f4cfcc282f8 in PyArray_GetCastingImpl (
    from=0x7f4cfd809420 <_ZN5boost6pythonL21class_metatype_objectE.lto_priv.0>, 
    to=to@entry=0x55c30af94350) at numpy/core/src/multiarray/convert_datatype.c:76
#2  0x00007f4cfcc28a1d in PyArray_GetCastSafety (from=0x55c30b2c3fa0, 
    to=0x7f4cfcf29140 <DOUBLE_Descr>, to_dtype=0x55c30af94350)
    at numpy/core/src/multiarray/convert_datatype.c:420
#3  0x00007f4cfccbffaa in PyArray_EquivTypes (type2=<optimized out>, type1=<optimized out>)
    at numpy/core/src/multiarray/multiarraymodule.c:1480
#4  PyArray_EquivTypes (type1=<optimized out>, type2=<optimized out>)
    at numpy/core/src/multiarray/multiarraymodule.c:1471
#5  0x00007f4d041c9c0b in boost::python::numpy::equivalent (a=..., b=...)
    at libs/python/src/numpy/dtype.cpp:125
#6  0x00007f4d041ca1ad in boost::python::numpy::(anonymous namespace)::array_scalar_converter<double>::convertible (obj=0x7f4c8fb92e80) at libs/python/src/numpy/dtype.cpp:162
#7  0x00007f4cfd7e274e in boost::python::converter::rvalue_from_python_stage1 (
    source=0x7f4c8fb92e80, converters=...) at libs/python/src/converter/from_python.cpp:54
#8  0x00007f4cfe2fbf48 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (*)(_object*, std::shared_ptr<espressopp::System>, double), boost::python::default_call_policies, boost::mpl::vector4<void, _object*, std::shared_ptr<espressopp::System>, double> > >::operator()(_object*, _object*) () from /home/espressopp/espressopp-build/_espressopp.so
```

The segfault appears with Python 3.10. Versions below 3.10 do not show this segfault. It seems like some conversion/wrong type problem.

**Comment by XzzX** [comment]
I think it tries to call the wrong constructor.

**Comment by fedepad** [comment]
> === STATUS REPORT === SegFault in `12/84 Test #10: testCapForce .........................***Exception: SegFault 1.18 sec` Line of error: `https://github.com/espressopp/espressopp/blob/junghans-patch-2/testsuite/cap_force/testCapForce.py#L111` Stacktrace with demangled names:
> 
> ```
> Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
> 0x00007f4d05c749eb in PyDict_GetItemWithError (op=0x7f4cfd7ec3f0 <boost::python::objects::enum_repr(PyObject*)>, key=key@entry=0x55c30af94350) at /usr/src/debug/python3.10-3.10.0-1.fc35.x86_64/Objects/dictobject.c:1513
> 1513        if (!PyDict_Check(op)) {                                                                 
> (gdb) bt
> #0  0x00007f4d05c749eb in PyDict_GetItemWithError (
>     op=0x7f4cfd7ec3f0 <boost::python::objects::enum_repr(PyObject*)>, key=key@entry=0x55c30af94350)
>     at /usr/src/debug/python3.10-3.10.0-1.fc35.x86_64/Objects/dictobject.c:1513
> #1  0x00007f4cfcc282f8 in PyArray_GetCastingImpl (
>     from=0x7f4cfd809420 <_ZN5boost6pythonL21class_metatype_objectE.lto_priv.0>, 
>     to=to@entry=0x55c30af94350) at numpy/core/src/multiarray/convert_datatype.c:76
> #2  0x00007f4cfcc28a1d in PyArray_GetCastSafety (from=0x55c30b2c3fa0, 
>     to=0x7f4cfcf29140 <DOUBLE_Descr>, to_dtype=0x55c30af94350)
>     at numpy/core/src/multiarray/convert_datatype.c:420
> #3  0x00007f4cfccbffaa in PyArray_EquivTypes (type2=<optimized out>, type1=<optimized out>)
>     at numpy/core/src/multiarray/multiarraymodule.c:1480
> #4  PyArray_EquivTypes (type1=<optimized out>, type2=<optimized out>)
>     at numpy/core/src/multiarray/multiarraymodule.c:1471
> #5  0x00007f4d041c9c0b in boost::python::numpy::equivalent (a=..., b=...)
>     at libs/python/src/numpy/dtype.cpp:125
> #6  0x00007f4d041ca1ad in boost::python::numpy::(anonymous namespace)::array_scalar_converter<double>::convertible (obj=0x7f4c8fb92e80) at libs/python/src/numpy/dtype.cpp:162
> #7  0x00007f4cfd7e274e in boost::python::converter::rvalue_from_python_stage1 (
>     source=0x7f4c8fb92e80, converters=...) at libs/python/src/converter/from_python.cpp:54
> #8  0x00007f4cfe2fbf48 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (*)(_object*, std::shared_ptr<espressopp::System>, double), boost::python::default_call_policies, boost::mpl::vector4<void, _object*, std::shared_ptr<espressopp::System>, double> > >::operator()(_object*, _object*) () from /home/espressopp/espressopp-build/_espressopp.so
> ```
> 
> The segfault appears with Python 3.10. Versions below 3.10 do not show this segfault. It seems like some conversion/wrong type problem.

Looks like is going down numpy...
So couple of things to check:
- numpy version installed in the env: because starting only with https://github.com/numpy/numpy/releases/tag/v1.21.3 numpy supports python 3.10
- if the first point is met: which version is used by boost python? In addition, I believe the followings are relevant for this:
  https://github.com/boostorg/python/issues/376
  https://github.com/numpy/numpy/pull/20507
  
 So for now, my understanding is to wait for the fix in boost python when numpy >= 1.21 might solve what is seen here.

**Comment by XzzX** [comment]
Thanks @fedepad for the hints. Indeed, we decided to wait a little bit for boost.python and numpy to get used to Python 3.10 and revert to Python 3.9 in the meantime.

**Review by XzzX — APPROVED** [review]

**Pull request merged**
