### PR TITLE
Particle distribution to CPU in MeanSquareInternalDist

### PR DESCRIPTION
**Pull request by hidekb**
The class MeanSquareInternalDist calculate the distance between particles belonging to a same polymer. Hence, particles should be distributed to CPU for each polymer.
I implemented this modification to MeanSquareInternalDist.hpp

### CODE REVIEW

**Comment by govarguz** [comment]
@hidekb In order to do so you identify particles belonging to every polymer get local particles per Processor (CPU) and then unfold them so that you count only local particles?

**Comment by hidekb** [comment]
@govarguz In MeanSquareInternalDist (ConfigsParticleDecomp), particles properties are stored into a data structure "configurations". The MeanSquareInternalDist class calculates the physical quantities using the particle configurations in the data structure "configurations". I think that there are no differences between real and local particles in the data structure "configurations".

**Comment by govarguz** [comment]
@hidekb I see, LGTM

**Comment by niktre** [comment]
@hidekb a very small test in the `testsuite/` would be great. It would also increase the coverage and thereby allow automatic merging of this PR.

**Comment by hidekb** [comment]
@niktre Thank you for your suggestion. I added test python script in the testuite/.

**Comment by govarguz** [comment]
LVGTM

**Pull request merged**
