### PR TITLE
Fix warning extra semicolon logger: warning: extra ';' inside a class [-Wextra-semi]

### PR DESCRIPTION
**Pull request by fedepad**
Running with -Wall -Wextra -pedantic on OSX 10.11.4 revealed (besides others...but just one at a time ;) ) a warning:

warning: extra ';' inside a class [-Wextra-semi]
      static LOG4ESPP_DECL_LOGGER(logger);

I fixed it. I have the logs from running make (~12 MB each) which I can share and the simple python script I used to count the total number of warnings generated, which I can also share.

Here the results:

Sum of warnings: 19198 for file output_pedantic_Wall_Werr_pedantic_no_fixed.txt
Sum of warnings: 17957 for file output_pedantic_Wall_fixed_doublesemicolons_warnings_forlogger_all_should_reducewarnings.txt

So the amount of warnings suppressed with this change is: 19198 - 17957 = 1241; 
at least with my version of OSX 10.11.4 and clang. I can also share the output from when cmake . is run.

I didn't expect to be so high, since 
static LOG4ESPP_DECL_LOGGER(logger);

doesn't appear like everywhere...but these are the numbers I get. Someone else should run it too maybe. Or enable a run to check that on Travis.

Tests pass on my machine.
Copyright has been updated on touched files.
Wait for tests on Travis.

### CODE REVIEW

**Comment by MrTheodor** [comment]
AFAIK this should be fixed in ```include/log4espp.hpp```;
it's natural to have a semicolon regardless of a macro or an attribute. Generally, semicolons in macros can cause tricky to spot bugs..

**Comment by fedepad** [comment]
@MrTheodor Yes, and that's basically the only file I touched...

**Comment by MrTheodor** [comment]
@fedepad true, sorry...

**Comment by fedepad** [comment]
Should I assign to someone in particular?

**Comment by MrTheodor** [comment]
Could you also clean lines 424-426 in ```include/log4espp.hpp``` ?

**Comment by fedepad** [comment]
@MrTheodor Yes, I've already done it in my local copy after I pushed...I will push then!

**Comment by fedepad** [comment]
Pushed. Wait for Travis, but it ran fine on my system before. 
Total number of warnings doesn't change with respect to previous commit (with respect to reduced number).

**Comment by fedepad** [comment]
Because of merging  #101 this branch is out-of-date with base branch. I can merge master into it and re-push.

**Comment by fedepad** [comment]
I confirm (at least on my system and with all the flags mentioned at the beginning) that all the existing warnings of that kind [-Wextra-semi] are removed by the changes in this PR:

$ python check_total_warnings.py

# total warnings: 19198 for file output_pedantic_Wall_Werr_pedantic_no_fixed.txt
# extra semicolons warnings: 1241 for file output_pedantic_Wall_Werr_pedantic_no_fixed.txt

# total warnings: 17957 for file output_pedantic_Wall_fixed_should_reducewarnings.txt
# extra semicolons warnings: 0 for file output_pedantic_Wall_fixed_should_reducewarnings.txt

**Pull request merged**
