### PR TITLE
Fix printf format warning

### PR DESCRIPTION
**Pull request by fedepad**
Long int variables were formatted in printf as int. Just changed to the right formatting for that type and in this way removed the warning from Clang in OSX.

### CODE REVIEW

**Comment by fedepad** [comment]
@junghans I added only a letter to the format identifier in a printf. What's the problem with codecov/patch failing?

**Comment by junghans** [comment]
The merge is effectually de-creasing the code coverage % and hence does the check fail.
I will merge it after you did a copyright update.

**Comment by fedepad** [comment]
Should I just put 2016 in addition to the ones already there or should I add also add 2014,2015 ?

**Comment by junghans** [comment]
Just add 2016

**Comment by fedepad** [comment]
Just wait until the last commit ends in travis, since I had to fix the first copyright, the right date for JGU Mainz to be in (e.g. wasn't there in 2012).

**Pull request merged**
