### PR TITLE
Further enabling multiple communicator

### PR DESCRIPTION
**Pull request by govarguz**
Further enabling multiple communicator. All within one commit!

### CODE REVIEW

**Comment by MrTheodor** [comment]
Sorry to bother, but is this line not implemented in pmi.workerIsActive already ?

**Comment by govarguz** [comment]
good point! the added line do not apply to all files handling communicators

**Comment by niktre** [comment]
Why did you kill all David's documentation lines and reverted to the original pre-David style with strange 'The (local) fixed pair list.'???

**Comment by junghans** [comment]
Copyright years need update, too!

**Pull request merged**
