### PR TITLE
fix missing mpip logo

### PR DESCRIPTION
**Pull request by niktre**

### CODE REVIEW

**Comment by junghans** [comment]
While you are at it, you might want to update the authors of the pdf manual.

**Comment by niktre** [comment]
@junghans of course, thanks!

**Comment by niktre** [comment]
@junghans now I'm stuck. Who do you think should be the authors? Everybody?

**Comment by junghans** [comment]
Just put "Development team" or something like that.

**Comment by niktre** [comment]
@acfogarty ok, now I added what I wanted. You only need to wait till all the checks are passed

**Pull request merged**
