### PR TITLE
Dynamically created exclusion list for Verlet List

### PR DESCRIPTION
**Pull request by jkrajniak**
- added new type of exclusion list for VerletList (dynamically created from new entries in fixed pair lists)
- minor changes in AddNewPotential (title)
- added signals for fixed lists: onTupleAdded, onTupleRemoved
- added method remove
- added new particle property (res_id -> residue id or molecule id)

### CODE REVIEW

**Comment by MrTheodor** [comment]
@govarguz 
The old add() method is still there: https://github.com/espressopp/espressopp/pull/172/files?diff=unified#diff-10cf35716bb762ce4795f961737c707cR72

**Comment by niktre** [comment]
@MrTheodor @govarguz @hidekb what is the status now of this PR?

**Comment by MrTheodor** [comment]
@niktre, @govarguz  I have changed the names of the methods. Regarding the regression tests, this should be a separate PR;

**Comment by jkrajniak** [comment]
Too many conflicts, closing for now.

**Pull request closed without merging**
