### PR TITLE
enable make install in ci

### LINKED ISSUE #349: fix install in CMake

### PR DESCRIPTION
**Pull request by XzzX**
closes #349

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Comment by junghans** [comment]
We need to set CMAKE_INSTALL_PATH or use sudo for install

**Comment by XzzX** [comment]
> We need to set CMAKE_INSTALL_PATH or use sudo for install

Why are we not root inside the container?

**Comment by junghans** [comment]
Some tools e.g. MPI don't work as root. Also running as root is really bad practice as the CI won't be able to catch file permission issue.

**Comment by XzzX** [comment]
> Some tools e.g. MPI don't work as root. Also running as root is really bad practice as the CI won't be able to catch file permission issue.

Hmm, all third-party containers I know (not many) do not create user accounts. I think this makes inheriting from it harder. Nevertheless, I agree that, in general, running stuff as root is not optimal. ;) 

Btw. MPI can run as root, `--allow-run-as-root`.

**Comment by junghans** [comment]
Yeah, the user in our containers has `sudo` rights, so one can still become root if needed.

**Pull request merged**
