### PR TITLE
option to automatically look for and use ccache

### PR DESCRIPTION
**Pull request by XzzX**
Are you interested in automatic ccache detection?  
Implementation according to:
https://cliutils.gitlab.io/modern-cmake/chapters/features/utilities.html

### CODE REVIEW

**Review by junghans — COMMENTED** [review]
Hmm, I am not sure why this is needed.

```
export PATH=/usr/lib64/ccache:${PATH}
```
is the usual way to enable ccache.

On the other hand it won't hurt.

**Comment by XzzX** [comment]
> Hmm, I am not sure why this is needed.
> 
> ```
> export PATH=/usr/lib64/ccache:${PATH}
> ```
> 
> is the usual way to enable ccache.
> 
> On the other hand it won't hurt.

The point of this PR is not to make finding `ccache` easier. In a default installation it will be in the search path anyway. It makes enabling `ccache` easier, i.e. removing the need for `export CXX="ccache g++"` or something similar.

You can use `cmake -DUSE_CCACHE=ON` and cmake will locate and configure it correctly if it is installed.

I think it is personal preference but might come in handy for example in IDEs if accessing environment variables is tricky.

**Comment by junghans** [comment]
Sure, as I said it won't hurt.

**Review by junghans — APPROVED** [review]

**Comment by junghans** [comment]
We should enable ccache support in github actions as well.
```
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      CCACHE_MAXSIZE: "10G"
      - name: Cache ccache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.distro }}-${{github.run_id}}
          restore-keys: ccache-${{ matrix.distro }}
```

**Comment by XzzX** [comment]
CCache support in GitHub actions can be enabled separately.

**Pull request merged**
