### PR TITLE
Fixed Minimizeenergy and implementation of variable Gamma step

### PR DESCRIPTION
**Pull request by hidekb**
Fixed MinimizeEnergy of measurement  of particles movement distance.
Implementation of the variable Gamma step in steepestDescentStep().

### CODE REVIEW

**Comment by govarguz** [comment]
It looks neat and more than adding variable Gamma. It is much faster than the former version since particle movement has been initialized and goes along to Fmax. However you need to update the copyright!

**Comment by junghans** [comment]
Btw, one can get a diff without whitespace changes by adding `?w=1` to diff url, e.g.:
<https://github.com/espressopp/espressopp/pull/89/files?w=1>

**Comment by MrTheodor** [comment]
@junghans thanks for tip, better than nothing... but this is rather a case of not having defined code style

Although code was already pushed, the text in docs does not reflect the variable gamma flag anymore. And it would be good to have unit test that will cover the flag and perhaps the error with max_DP.

**Comment by hidekb** [comment]
Thanks you for the suggestion. I will add the explanation of using a variable gamma flag.

**Pull request merged**
