### PR TITLE
Merge Piadress

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by kkreis** [comment]
I am still heavily developing my Path Integral H-AdResS in this branch, although in my own fork. It is not yet ready to be merged into the master.

**Comment by junghans** [comment]
So can be get rite of the [PIadress](https://github.com/espressopp/espressopp/tree/PIadress) branch on [espressopp/espressopp](https://github.com/espressopp/espressopp) then?

**Comment by kkreis** [comment]
I think we can indeed, yes. Then I will finish it in my own fork and eventually merge it once it works.

**Comment by junghans** [comment]
Bye bye PIadress branch!

**Pull request closed without merging**
