### PR TITLE
rely on requirements.txt for python dependencies

### PR DESCRIPTION
**Pull request by XzzX**

### CODE REVIEW

**Review by fedepad — COMMENTED** [review]
Are there any specific version requirements for the python packages or it is fine as is?

**Comment by XzzX** [comment]
> Are there any specific version requirements for the python packages or it is fine as is?

Good point. I do not know. Perhaps someone with more experience with the framework can tell.

**Comment by junghans** [comment]
It would be nice to know how long the installation with pip takes once we purge stuff from the containers.

**Comment by XzzX** [comment]
> It would be nice to know how long the installation with pip takes once we purge stuff from the containers.

What do you suggest apart from trying it out? I do not think it will take too long. I think it will download binary wheels.

**Review by junghans — APPROVED** [review]

**Pull request merged**
