### PR TITLE
move CI to docker

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by niktre** [comment]
what about clang compiler and opensuse os? is it possible to include them as well?

**Comment by junghans** [comment]
clang builds are done! 

For Opensuse you need to create a build environment and put it in the espressopp/buildenv repo.

**Comment by junghans** [comment]
This is ready to merge, I will add MPICH and OpenSuse builds in a latter pull request.

**Comment by junghans** [comment]
@niktre & @govarguz : MPICH builds are now included.

OpenSuse is a bit harder as they dropped mpi4py in leap-42, but let's see if we get it back in:
https://build.opensuse.org/request/show/445325

**Comment by junghans** [comment]
mpi4py on its way back in OpenSuse:
https://build.opensuse.org/request/show/445611

**Comment by junghans** [comment]
ping @govarguz

**Comment by niktre** [comment]
ok, now I understand better. 

@junghans:
1. could you also add "getting ESPResSo++ from docker" to README?

2. is it possible now to run ESPResSo++ under Windows?

**Comment by junghans** [comment]
1.) Done in 7bc54d6b2c37cedd456bfa219476ae24e31a206a
2.) Docker work on windows too: https://www.docker.com/products/docker#/windows

**Pull request merged**
