### PR TITLE
Fix CI

### LINKED ISSUE #250: AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'
All the CI is broken with the following error:
```
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'
```
details here:https://travis-ci.org/espressopp/espressopp/jobs/472171056

### PR DESCRIPTION
**Pull request by junghans**
Fix #250

### CODE REVIEW

**Comment by junghans** [comment]
Thanks @jkrajniak

**Comment by govarguz** [comment]
@junghans, I was refering to the multicore tests for n=2 and 3, which are not really needed, since DDecompositon for LB did not change

**Comment by junghans** [comment]
@junghans even if nothing changed, shouldn't it run for `n=2` as well?

**Comment by niktre** [comment]
well, now Adress tests are failing at `espressopp.storage.DomainDecompositionAdress.invalidateGhosts`

**Comment by junghans** [comment]
Might be related to #230

**Comment by niktre** [comment]
There is at least a difference in the versions of the compiler. 
On Ubuntu distro it is 7.3.0:
`-- The C compiler identification is GNU 7.3.0`
On Fedora distro it is 8.2.1:
`-- The C compiler identification is GNU 8.2.1`
On OpenSuse it is 7.3.1:
`-- The C compiler identification is GNU 7.3.1`

Can it be the reason?

**Comment by jkrajniak** [comment]
On fedora, untangled stack trace:
```
espressopp::storage::DomainDecompositionAdress::invalidateGhosts()
espressopp::storage::DomainDecompositionAdress::decompose()
espressopp::integrator::VelocityVerlet::run(int)
boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (espressopp::integrator::MDIntegrator::*)(int), boost::python::default_call_policies, boost::mpl::vector3<void, espressopp::integrator::MDIntegrator&, int> > >::operator()(_object*, _object*)
boost::python::objects::function::call(_object*, _object*) const
boost::python::handle_exception_impl(boost::function0<void>)
```
on `ubuntu_rolling` the gcc is: `gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0`

**Comment by niktre** [comment]
@jkrajniak great!

**Comment by jkrajniak** [comment]
I'm wondering what was the reason of the difference in behavior, and why the previous version of the code works correctly with some compilators. The current version is the idiomatic way of removing elements using iterators

**Comment by niktre** [comment]
@jkrajniak could you explain how you identified a problem? :-)

**Comment by jkrajniak** [comment]
@niktre; sure I have installed `gdb` in docker container. Then I run bash, with permissions to allow working gdb
 ```docker run --security-opt seccomp=unconfined -it espressopp:fix bash```.
Next, I have installed gdb, vim and recompilled  espressopp with `cmake -DCMAKE_RELEASE_TYPE=Debug` and run the test in the gdb
```
gdb --args /usr/bin/python2 "/home/espressopp/espressopp/testsuite/AdResS/RDFatomistic/test_RDFatomistic.py"
```
the gdb stops at the line where the test fails
```
Thread 1 "python2" received signal SIGSEGV, Segmentation fault.
espressopp::storage::DomainDecompositionAdress::invalidateGhosts (this=0x555555f37010) at /home/espressopp/espressopp/src/storage/DomainDecompositionAdress.cpp:329
329	        if (vp->ghost()) {
(gdb) l
324	    clearAdrATParticlesG();
325	    // clear ghost tuples
326	    FixedTupleListAdress::iterator it = fixedtupleList->begin();
327	    for (;it != fixedtupleList->end(); ++it) {
328	        Particle* vp = it->first;
329	        if (vp->ghost()) {
330	            //std::cout << "erasing ghost particle in tuple: " << vp->id() << "-" << vp->ghost() << "\n";
331	            fixedtupleList->erase(it);
332	        }
333	    }
```

I remembered that there was some issue with removing elements during the looping.

**Comment by niktre** [comment]
@jkrajniak thanks! I was on a similar way: got `docker` with `gdb` support but haven't thought on the removing elements issue. Instead, I concentrated on the modules/libraries mix, what appears to be a bad decision :-)

**Pull request merged**
